server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.66:8848
        #server-addr: 192.168.0.66:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
