server:
  port: 3344

spring:
  application:
    name: cloud-config-center   # 注册进 eureka 服务器的微服务名

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangzhongxun/springcloud-config.git    # GitHub 上面的 git 仓库名称
          # 搜索目录
          search-paths:
            - springcloud-config
      # 读取分支
      label: master

# 服务注册到 eureka 地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
