server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.66:8848    # 配置 Nacos 地址
        #server-addr: 192.168.0.66:8848    # 配置 Nacos 地址
        #server-addr: 192.168.1.66:1111    # 换成 Nginx 的 1111 端口，做集群

management:
  endpoints:
    web:
      exposure:
        include: "*"
