server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.66:8848    # 配置 Nacos 地址
        #server-addr: 192.168.0.66:8848    # 配置 Nacos 地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
