server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

# 用于服务降级 在注解 @FeignClient 中添加 fallbackFactory 属性值
feign:
  hystrix:
    enabled: true
